___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lesson, Session - 2</p><h1>

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [3]:
arr[8]

8

In [5]:
arr[-3]

8

In [6]:
arr[2:5]

array([2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[1::2]

array([1, 3, 5, 7, 9])

## Indexing a 2D array (matrices)

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>. I recommend usually using the comma notation for clarity.</p>

In [9]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])


In [10]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
arr_2d[0,:]

array([ 5, 10, 15])

In [12]:
arr_2d[0]

array([ 5, 10, 15])

In [13]:
arr_2d[1][1]

25

In [14]:
arr_2d[1,1]

25

In [15]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [16]:
arr_2d[2,1] = 99

In [17]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 99, 45]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [18]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [19]:
v[[3,5,7]]

array([ 9, 15, 21])

In [20]:
arr2d=np.zeros((10,10),dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
for i in range(len(arr2d)):
    arr2d[i] = i

arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [22]:
arr2d[[2,4,6]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

<h3>any_array[[row indices], [column indices]]</h3>

In [24]:
jj=np.arange(1,17).reshape(4,4)
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
jj[[1,2],[0,3]]

array([ 5, 12])

In [26]:
jj[2,[2,3]]

array([11, 12])

In [27]:
jj[[2,3], 1]

array([10, 14])

### Using ***basic index*** and ***fancy index*** together

In [28]:
jj[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

### Using ***basic slicing*** and ***fancy index*** together

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

# Selection on a Condition

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [30]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [32]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [33]:
arr[(arr>3)&(arr<8)]

array([4, 5, 6, 7])

In [35]:
arr[arr!=4]

array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10])

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

https://numpy.org/doc/stable/user/theory.broadcasting.html

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[:5] = 99

In [38]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [40]:
arr_slice = arr[5:]
arr_slice

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr_slice[-2 :] = 55
arr_slice  

array([ 5,  6,  7,  8, 55, 55])

In [42]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8, 55, 55])

In [43]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8, 55, 55])

In [44]:
arr_copy[2:6] = 0
arr_copy

array([99, 99,  0,  0,  0,  0,  6,  7,  8, 55, 55])

In [45]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8, 55, 55])

# NumPy Operations

## Arithmetic Operations

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [46]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [49]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
import warnings
warnings.filterwarnings('ignore')

In [51]:
arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [52]:
1 / arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [53]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [54]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [55]:
arr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Universal Array Functions

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [58]:
np.exp(arr) # exponential

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [59]:
np.sin(np.pi/4)

0.7071067811865476

In [60]:
np.tan(np.pi/4)

0.9999999999999999

In [61]:
np.pi

3.141592653589793

In [62]:
np.log(1000)

6.907755278982137

In [63]:
np.log10(100)

2.0

## Statistical Calculations

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``np.corrcoef(arr)`` | Returns correlation coefficient of array

In [64]:
v=np.array([1,1,2,2,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [65]:
np.mean(v)

2.142857142857143

In [66]:
v.mean()

2.142857142857143

In [67]:
v.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [68]:
np.median(v)

2.0

In [69]:
v.std()

0.8329931278350429

In [70]:
np.std(v)

0.8329931278350429

In [71]:
v.var()

0.6938775510204082

In [72]:
np.var(v)

0.6938775510204082

In [83]:
np.random.seed(42)
xarr = np.random.randn(5,3)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [84]:
np.mean(xarr)

0.010348524333336447

In [85]:
xarr.std()

0.9604457089189911

In [88]:
xarr[2,2]

-0.4694743859349521

In [92]:
xarr[[2,1]]

array([[ 1.57921282,  0.76743473, -0.46947439],
       [ 1.52302986, -0.23415337, -0.23413696]])

In [86]:
np.corrcoef(xarr)

array([[ 1.        ,  0.33500663, -0.29669929,  0.3331251 ,  0.40829585],
       [ 0.33500663,  1.        ,  0.80039247,  0.99999801,  0.99688316],
       [-0.29669929,  0.80039247,  1.        ,  0.80158756,  0.75060382],
       [ 0.3331251 ,  0.99999801,  0.80158756,  1.        ,  0.99672369],
       [ 0.40829585,  0.99688316,  0.75060382,  0.99672369,  1.        ]])

# The End of the Session - 2

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.