___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>

# Pandas Series

In [1]:
import pandas as pd

In [3]:
import numpy as np

## Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [2]:
pd.Series.__doc__

"\n    One-dimensional ndarray with axis labels (including time series).\n\n    Labels need not be unique but must be a hashable type. The object\n    supports both integer- and label-based indexing and provides a host of\n    methods for performing operations involving the index. Statistical\n    methods from ndarray have been overridden to automatically exclude\n    missing data (currently represented as NaN).\n\n    Operations between Series (+, -, /, *, **) align values based on their\n    associated index values-- they need not be the same length. The result\n    index will be the sorted union of the two indexes.\n\n    Parameters\n    ----------\n    data : array-like, Iterable, dict, or scalar value\n        Contains data stored in Series. If data is a dict, argument order is\n        maintained.\n    index : array-like or Index (1d)\n        Values must be hashable and have the same length as `data`.\n        Non-unique index values are allowed. Will default to\n        RangeIn

In [4]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [5]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [7]:
arr

array([10, 20, 30])

In [8]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int32

In [10]:
pd.Series(data=arr, index=labels).loc['a']

10

In [11]:
pd.Series(data=arr, index=labels).iloc[0]

10

### **Using Dictionary**

In [12]:
d

{'a': 10, 'b': 20, 'c': 30}

In [13]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [15]:
pd.Series(d, index=['x','b','z'])

x     NaN
b    20.0
z     NaN
dtype: float64

In [16]:
type(np.nan)

float

### Using Scalar Value

In [17]:
pd.Series(data='Jason')

0    Jason
dtype: object

In [18]:
pd.Series(data='Jason', index=range(1,5))

1    Jason
2    Jason
3    Jason
4    Jason
dtype: object

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [20]:
set1 = (1,2,3,6)

In [21]:
pd.Series(set1)

0    1
1    2
2    3
3    6
dtype: int64

In [22]:
pd.Series([set, list, dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [23]:
pd.Series([set, list, dict])[0]([2,5,7,5,8,2])

{2, 5, 7, 8}

In [26]:
func_all = pd.Series([sum,print,len])

In [27]:
func_all[0]([1,2,3,4,5])

15

In [29]:
mix_data = ['Aziz', 2, True]


In [30]:
ser = pd.Series(mix_data)
ser

0    Aziz
1       2
2    True
dtype: object

In [31]:
ser.dtype

dtype('O')

In [32]:
type(ser)

pandas.core.series.Series

In [33]:
type(ser[0])

str

In [37]:
type(ser[1])

int

In [34]:
arr = np.array(mix_data)
arr

array(['Aziz', '2', 'True'], dtype='<U4')

In [35]:
type(arr[0])

numpy.str_

In [36]:
type(arr[1])

numpy.str_

In [38]:
pd.Series([set, list, dict])[2]([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

### Basic Attributes of Series

In [39]:
ser = pd.Series(np.random.randint(0,100,7))
ser

0    73
1    85
2    68
3    82
4    63
5    39
6     5
dtype: int32

In [40]:
type(ser)

pandas.core.series.Series

In [41]:
ser.shape

(7,)

In [42]:
ser.size

7

In [43]:
ser.ndim

1

In [44]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [45]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [53]:
for i in ser.index:
    print(i)

    

0
1
2
3
4
5
6


In [48]:
ser.keys

<bound method Series.keys of 0    73
1    85
2    68
3    82
4    63
5    39
6     5
dtype: int32>

In [49]:
ser.keys()

RangeIndex(start=0, stop=7, step=1)

In [50]:
ser.values

array([73, 85, 68, 82, 63, 39,  5])

In [61]:
ser.items()

In [62]:
list(ser.items())

[(0, 73), (1, 85), (2, 68), (3, 82), (4, 63), (5, 39), (6, 5)]

In [63]:
for index, value in ser.items():
    print(f"index: {index}, value: {value}")

index: 0, value: 73
index: 1, value: 85
index: 2, value: 68
index: 3, value: 82
index: 4, value: 63
index: 5, value: 39
index: 6, value: 5


In [65]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])
ser

c    21
b    18
a    22
e    21
f     5
d    18
g    13
i    11
h     6
j     2
dtype: int32

In [66]:
ser.head()

c    21
b    18
a    22
e    21
f     5
dtype: int32

In [67]:
ser.tail()

d    18
g    13
i    11
h     6
j     2
dtype: int32

In [69]:
ser.sample(3)

j     2
e    21
b    18
dtype: int32

In [71]:
ser.sort_index(ascending=True)


a    22
b    18
c    21
d    18
e    21
f     5
g    13
h     6
i    11
j     2
dtype: int32

In [73]:
ser.sort_values()

j     2
f     5
h     6
i    11
g    13
b    18
d    18
c    21
e    21
a    22
dtype: int32

In [74]:
ser

c    21
b    18
a    22
e    21
f     5
d    18
g    13
i    11
h     6
j     2
dtype: int32

In [77]:
ser.isin([6,5])

c    False
b    False
a    False
e    False
f     True
d    False
g    False
i    False
h     True
j    False
dtype: bool

In [78]:
pd.Series([i for i in 'calrusway'])

0    c
1    a
2    l
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [86]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [87]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [81]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [88]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [89]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [90]:
ser1[1]

2

In [92]:
ser1["Germany"]

2

In [93]:
ser1.Germany

2

Operations are then also done based off of index:

In [95]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [96]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [97]:
ser3[0]

'a'

In [98]:
ser3[:2]

0    a
1    b
dtype: object

In [101]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

### pandas_series[index] | pandas_series[[indices, indices...]]

In [103]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [104]:
panser[['terry', 'orion']]

terry    121
orion    150
dtype: int64

In [105]:
panser['terry': 'orion']

terry      121
micheal    200
orion      150
dtype: int64

In [106]:
panser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes

In [107]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [108]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [109]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [110]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [111]:
panser.items()

In [112]:
for index, value in panser.items():
    print(index, value)

terry 121
micheal 200
orion 150
jason 99


In [113]:
'terry' in panser

True

In [114]:
200 in panser.values

True

In [115]:
panser['terry'] = 90
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [116]:
panser.isin([200,150])

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [117]:
panser[panser>100] =175
panser

terry       90
micheal    175
orion      175
jason       99
dtype: int64